### PR TITLE
Enable 'output_format' for a file-based queries 

### PR DESCRIPTION
**Pull request by nikolamaric**
Set `output_format` to `json` by default and enable its setting in the `query` method.

### CODE REVIEW

**Comment by davecap** [comment]
Has this been tested with any format other than json? I don't think it works with csv/tsv.

**Comment by nikolamaric** [comment]
> Has this been tested with any format other than json? I don't think it works with csv/tsv.

It has been tested, and worked like a charm (I have done it now)

**Comment by nikolamaric** [comment]
fixes #392

**Comment by nikolamaric** [comment]
Seems we have some issues with Travis CI, as it has been stuck since Friday?

**Comment by davecap** [comment]
Ah yes, sorry travis has actually been replaced for the GH Actions. We can just ignore it.

**Comment by nikolamaric** [comment]
The PR is merged into #394. Closing.

**Pull request closed without merging**
