### PR TITLE
validate the object's full path before getting it by full path

### PR DESCRIPTION
**Pull request by davecap**

### CODE REVIEW

**Comment by jsh2134** [comment]
encountering an issue with this path. needs more debugging

`'solvebio:user-1411:/10__records bis/10_records (1)/New Dataset'`

**Comment by jsh2134** [comment]
```
In [2]: path
Out[2]: 'solvebio:user-1411:/10__records bis/10_records (1)/New Dataset'

In [3]: Object.validate_full_path(path)
Out[3]:
('solvebio:user-1411:/10__records bis/10_records (1)/New Dataset',
 {'domain': 'solvebio',
  'full_path': 'solvebio:user-1411:/10__records bis/10_records (1)/New Dataset',
  'path': '/10__records bis/10_records (1)/New Dataset',
  'vault': 'user-1411',
  'vault_full_path': 'solvebio:user-1411'})

In [4]: Object.get_by_full_path(path)
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
/Users/ganesha/code/solve/solvebio-python/solvebio/cli/ipython.pyc in <module>()
----> 1 Object.get_by_full_path(path)

/Users/ganesha/code/solve/solvebio-python/solvebio/resource/object.pyc in get_by_full_path(cls, full_path, **params)
    146         params.update({'full_path': full_path})
    147         return cls._retrieve_helper('object', 'full_path', full_path,
--> 148                                     **params)
    149
    150     @classmethod

/Users/ganesha/code/solve/solvebio-python/solvebio/resource/apiresource.pyc in _retrieve_helper(cls, model_name, field_name, error_value, **params)
    256         else:
    257             raise NotFoundError('No {0} found with {1} "{2}"'
--> 258                                 .format(model_name, field_name, error_value))
    259
    260     @classmethod

NotFoundError: No object found with full_path "solvebio:user-1411:/10__records bis/10_records (1)/New Dataset"

```

**Comment by jsh2134** [comment]
appears to be API

**Comment by davecap** [comment]
Fix the table fields for Vault and Object to show the full paths. We may also want to hide the vault type to avoid confusion.

**Pull request merged**
